# Generated by Django 5.2.17 on 2026-09-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='puntaje',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntaje'),
        ),
    ]
